# Generated by Django 5.2.8 on 2025-11-20 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("password", "Password"),
                            ("document", "Document"),
                            ("note", "Note"),
                            ("card", "Payment Card"),
                            ("identity", "Identity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(default="folder", max_length=50)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "name", "category_type")},
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("access_delay_days", models.IntegerField(default=7)),
                ("can_access_passwords", models.BooleanField(default=True)),
                ("can_access_documents", models.BooleanField(default=False)),
                ("can_access_notes", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "email")},
            },
        ),
        migrations.CreateModel(
            name="EmergencyAccessRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("verification_code", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                (
                    "emergency_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vault.emergencycontact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PasswordPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_length", models.IntegerField(default=12)),
                ("require_uppercase", models.BooleanField(default=True)),
                ("require_lowercase", models.BooleanField(default=True)),
                ("require_numbers", models.BooleanField(default=True)),
                ("require_symbols", models.BooleanField(default=True)),
                ("check_compromised_passwords", models.BooleanField(default=True)),
                ("auto_generate_passwords", models.BooleanField(default=True)),
                ("password_history_count", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_policy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VaultItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("password", "Password"),
                            ("document", "Document"),
                            ("note", "Secure Note"),
                            ("card", "Payment Card"),
                            ("identity", "Identity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("encrypted_data", models.TextField()),
                ("is_favorite", models.BooleanField(default=False)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("password_strength", models.IntegerField(blank=True, null=True)),
                ("is_compromised", models.BooleanField(default=False)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vault.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SecureFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("encrypted_file_path", models.CharField(max_length=500)),
                ("checksum", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vault_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="vault.vaultitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("create_item", "Create Item"),
                            ("update_item", "Update Item"),
                            ("delete_item", "Delete Item"),
                            ("view_item", "View Item"),
                            ("export_data", "Export Data"),
                            ("emergency_access", "Emergency Access"),
                            ("password_change", "Password Change"),
                            ("device_added", "Device Added"),
                            ("device_removed", "Device Removed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(blank=True, max_length=50)),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("device_id", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="vault_audit_user_id_886427_idx",
                    ),
                    models.Index(
                        fields=["user", "action"], name="vault_audit_user_id_5f5219_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="vaultitem",
            index=models.Index(
                fields=["user", "item_type"], name="vault_vault_user_id_c5e6a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaultitem",
            index=models.Index(
                fields=["user", "is_favorite"], name="vault_vault_user_id_35c6e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaultitem",
            index=models.Index(
                fields=["user", "category"], name="vault_vault_user_id_2f60ff_idx"
            ),
        ),
    ]
